In [2]:
import numpy as np

In [3]:
my_list=[10,20,30,40,50,60]

In [4]:
np.array(my_list)

array([10, 20, 30, 40, 50, 60])

In [5]:
my_numpy_array=np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.mean()

np.float64(35.0)

In [9]:
my_numpy_array.min()

np.int64(10)

In [10]:
my_numpy_array

array([10, 20, 30, 40, 50, 60])

In [12]:
matrix_list=[[1,0,1],[0,0,1],[0,0,1],[0,1,0]]

In [14]:
matrix_numpy=np.array(matrix_list)

In [15]:
matrix_numpy

array([[1, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0]])

In [16]:
matrix_numpy.shape

(4, 3)

In [41]:
np.random.randint(90,100)

98

In [43]:
yeni_list=np.random.randint(1,150,25)

In [44]:
yeni_list

array([ 53, 111,  71,  39,  15, 142,  75, 149, 137,  24,  91,  60, 148,
        92,  20,  77,  33,  29,  63, 128,  87,  80,  42, 126,  50],
      dtype=int32)

In [45]:
yeni_list>50

array([ True,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True, False, False,
        True,  True,  True,  True, False,  True, False])

In [46]:
yeni_list>98

array([False,  True, False, False, False,  True, False,  True,  True,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False])

In [47]:
result_array=yeni_list>98

In [48]:
result_array

array([False,  True, False, False, False,  True, False,  True,  True,
       False, False, False,  True, False, False, False, False, False,
       False,  True, False, False, False,  True, False])

In [49]:
yeni_list[result_array]

array([111, 142, 149, 137, 148, 128, 126], dtype=int32)